FROM nginx

COPY index.html /usr/share/nginx/html/index.html


# docker build -t std-web
# docker run -d -p 8050:8050 --name std-server std-web

# Dockerfile - 도커 이미지를 설계하는 작업

# Dockerfile -> 명령어 : docker build -> 이미지 생성
#  -> 명령어 : docker run -> 컨테이너 생성 및 실행

# 설계도 -> 설계도로 만든 실행 패키지 -> 실제 실행
# Dockerfile -> Image      ->      -> Container


